### ISSUE TITLE
Error.captureStackTrace not defined in browser

### ISSUE THREAD

**Issue by benallfree** [bendrucker/micro-req#1]
Hello, I like what you're doing here!

Just wanted to give you a heads up that `nested-error-stacks` is not compatible with all browsers. See https://github.com/mdlavin/nested-error-stacks/issues/9.

I don't have an immediate solution to this, just letting you know.

**Comment by bendrucker** [comment]
https://github.com/mdlavin/nested-error-stacks/pull/6 ;)

I've actually switched to https://github.com/jam3/xhr-request and forgot to deprecate this lib. Will do that later today.
